resolver: lts-7.1

compiler: ghc-8.0.1
compiler-check: match-exact

packages:
- '.'
- location:
    git: https://github.com/haskoin/haskoin.git
    commit: e11ff9b8375ea07bf72420401898f9d607476bb2
  extra-dep: true
  subdirs:
    - haskoin-core
    - haskoin-node
    - haskoin-wallet
- location:
    git: https://github.com/runeksvendsen/rbpcp-api.git
    commit: c4debaa3c4d9bd020b8608e05a04e66133bd474e 
  extra-dep: true
- location:
    git: https://github.com/runeksvendsen/blockchain-restful-address-index-api.git
    commit: 8961a304e87f3e83caee7c437d4996841f50ede6
  extra-dep: true
- location:
    git: https://github.com/runeksvendsen/bitcoin-payment-protocol.git
    commit: da60b36560ba48642f0c80f2944921d2ce7ef37d
  extra-dep: true


# Haskoin dependencies
extra-deps:
- murmur3-1.0.3
- pbkdf-1.1.1.1
- secp256k1-0.4.6
- proto-lens-0.1.0.5
